# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trafikoa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trafikoa

  pod 'AEXML'
  pod 'Alamofire', '~> 4.7'

  target 'TrafikoaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrafikoaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
